export const ItemTypes = {
    PLUGS: 'Plugs',
    SOCKETS: 'Sockets',
    PILOT_LIGHTS: 'Pilot Lights',
    MULTIMETER: 'Multimeter',
    LIVE_PINS_INPUT: 'Live Pins Input',
    LIVE_PINS_OUTPUT: 'Loop Through',
    PINS_INPUT_1: 'Pins Input@1',
    PINS_INPUT_2: 'Pins Input@2',
    PLUGS_1: 'Plugs@1',
    PLUGS_2: 'Plugs@2',
    PLUGS_3: 'Plugs@3',
    PLUGS_4: 'Plugs@4',
    PLUGS_5: 'Plugs@5',
    SOCKETS_1: 'Sockets@1',
    SOCKETS_2: 'Sockets@2',
    SOCKETS_3: 'Sockets@3',
}
